apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    fdk.service: elasticsearch5
  name: elasticsearch5
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  - name: "9300"
    port: 9300
    targetPort: 9300
  selector:
    fdk.service: elasticsearch5
status:
  loadBalancer: {}
