apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: harvester
  name: harvester
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: harvester
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ required "Missing value" .Values.SPRING_PROFILES_ACTIVE }}
        - name: harvester_adminPassword
          value: {{ required "Missing value" .Values.FDK_HARVESTER_ADMINPASSWORD }}
        - name: harvester_adminUsername
          value: {{ required "Missing value" .Values.FDK_HARVESTER_ADMINUSERNAME }}
        image: {{ required "Missing value" .Values.HARVESTER_IMAGE }}
        imagePullPolicy: Always
        name: harvester
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value" .Values.FDK_HARVESTER_MEMORY | quote }}
        livenessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
      restartPolicy: Always
status: {}
