apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: harvester-api
  name: harvester-api
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: harvester-api
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ required "Missing value 1" .Values.SPRING_PROFILES_ACTIVE }}
        - name: emailUsername
          value: {{ .Values.FDK_HARVESTER_API_EMAILUSERNAME }}
        - name: emailPassword
          value: {{ .Values.FDK_HARVESTER_API_EMAILPASSWORD }}
        - name: emailSenderAddress
          value: {{ .Values.FDK_HARVESTER_API_EMAILSENDERADDRESS }}
        - name: themesHttpUsername
          value: {{ required "Missing value" .Values.FDK_HARVESTER_API_THEMESHTTPUSER }}
        - name: themesHttpPassword
          value: {{ required "Missing value" .Values.FDK_HARVESTER_API_THEMESHTTPPASSWORD }}
        - name: FDK_ES_CLUSTERNODES
          value: {{ required "Missing value" .Values.FDK_ES_CLUSTERNODES }}
        - name: FDK_ES_CLUSTERNAME
          value: {{ required "Missing value" .Values.FDK_ES_CLUSTERNAME }}
        - name: application_openDataEnhet
          value: {{ required "Missing value" .Values.FDK_HARVESTER_API_APPLICATION_OPENDATAENHET }}
        image: {{ required "Missing value" .Values.HARVESTER_API_IMAGE }}
        imagePullPolicy: Always
        name: harvester-api
        ports:
        - containerPort: 8080
        - containerPort: 8181
        resources: 
          requests:
            memory: {{ required "Missing value" .Values.FDK_HARVESTER_API_MEMORY | quote }}
      restartPolicy: Always
status: {}
