apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: harvester
  name: harvester
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: harvester
status:
  loadBalancer: {}
