apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    fdk.service: harvester-claim0
  name: harvester-claim0
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
