apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ required "Missing value" .Values.FDK_INGRESSNAME }}
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.global-static-ip-name: {{ required "Missing value" .Values.FDK_INGRESS_IP_NAME }}
spec:
  rules:
  - host: {{ required "Missing value" .Values.FDK_INGRESS_HOSTNAME_REG }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx-registration
          servicePort: 8080
  - host: {{ required "Missing value" .Values.FDK_INGRESS_HOSTNAME_WWW }}
    http:
      paths:
      - path: /*
        backend:
          serviceName: nginx-search
          servicePort: 8080
