apiVersion: v1
kind: Service
metadata:
  annotations:
  creationTimestamp: null
  labels:
    fdk.service: nginx-registration
  name: nginx-registration
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: nginx-registration
status:
  loadBalancer: {}
