apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    fdk.service: registration-api
  name: registration-api
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: registration-api
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_SPRING_PROFILES_ACTIVE | quote}}
        - name: FDK_ES_CLUSTERNODES
          value: {{ required "Missing value" .Values.FDK_ES_CLUSTERNODES | quote }}
        - name: FDK_ES_CLUSTERNAME
          value: {{ required "Missing value" .Values.FDK_ES_CLUSTERNAME | quote }}
        - name: registrationApi_apikey
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_KEY | quote }}
        - name: registrationApi_altinnServiceUrl
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_ALTINNSERVICEURL | quote }}
        - name: registrationApi_clientSSLCertificateKeystoreLocation
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_CLIENTSSLCERTIFICATEKEYSTORELOCATION | quote }}
        - name: registrationApi_clientSSLCertificateKeystorePassword
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_CLIENTSSLCERTIFICATEKEYSTOREPASSWORD | quote }}
        - name: registrationApi_harvesterPassword
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_HARVESTERPASSWORD | quote }}
        - name: registrationApi_harvesterUsername
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_HARVESTERUSERNAME | quote }}
        - name: registrationApi_ipKeyPassword
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_IPKEYPASSWORD | quote }}
        - name: registrationApi_ipStorePassword
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_IPSTOREPASSWORD | quote}}
        - name: reg_altinnServiceCode
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_ALTINNSERVICECODE | quote }}
        - name: reg_altinnServiceEdition
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_ALTINNSERVICEEDITION | quote }}
        - name: registrationApi_idportenMetadataFile
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_IDPORTENMETADATAFILE | quote }}
        - name: registrationApi_sslKeystoreLocation
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_SSLKEYSTORELOCATION | quote }}
        - name: registrationApi_sslKeyPassword
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_SSLKEYPASSWORD | quote }}
        - name: registrationApi_IncludeServerPortInRequestUrl
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_INCLUDESERVERPORTINREQUESTURL | quote }}
        - name: registrationApi_OpenshiftEnvironment
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_OPENSHIFTENVIRONMENT | quote }}
        - name: registrationApi_ServerName
          value: {{ required "Missing value" .Values.FDK_REGISTRATION_API_REGISTRATIONAPI_SERVERNAME | quote }}
        image: {{ required "Missing value" .Values.REGISTRATION_API_IMAGE }}
        imagePullPolicy: Always
        name: registration-api
        ports:
        - containerPort: 8080
        resources: 
          requests:
            memory: {{ required "Missing value" .Values.FDK_REGISTRATION_API_MEMORY | quote }}
        volumeMounts:
        - mountPath: /conf
          name: registration-api-claim0
      restartPolicy: Always
      volumes:
      - name: registration-api-claim0
        persistentVolumeClaim:
          claimName: registration-api-claim0
status: {}
