apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: search
  name: search
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    fdk.service: search
status:
  loadBalancer: {}
