apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: search
  name: search
  namespace: {{ required "Missing value" .Values.NAMESPACE }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: search
    spec:
      containers:
        - env:
          - name: NODE_ENV
            value: {{ required "Missing value" .Values.SEARCH_NODE_ENV }}
          image: {{ required "Missing value" .Values.SEARCH_IMAGE }}
          imagePullPolicy: Always
          name: search
          ports:
          - containerPort: 3000
          resources: 
            requests:
              memory: {{ required "Missing value" .Values.FDK_SEARCH_MEMORY | quote }}
      restartPolicy: Always
status: {}
